language: node_js
sudo: required
addons:
  chrome: stable
node_js:
- '8.11.4'
branches:
  only:
    - master
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - npm run test-ci
  - npm run build